### PR TITLE
Set direction of dotgraph by rankdir

### PR DESCRIPTION
**Pull request by wkentaro**
**rankdir=LR**

graph

### CODE REVIEW

**Comment by delta2323** [comment]
Now we have merged your previous PR on the computational graph (#1169), could you merge or rebase the latest branch?

**Comment by wkentaro** [comment]
rebased.

**Comment by delta2323** [comment]
Please add a test case where the value of `rankdir` option is different from four valid values.

**Comment by wkentaro** [comment]
Added.

**Comment by delta2323** [comment]
Thank you for your PR!

**Comment by wkentaro** [comment]
Thank you.

2016年5月30日月曜日、Kenta Oono<notifications@github.com>さんは書きました:

> Merged #1218 <https://github.com/pfnet/chainer/pull/1218>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pfnet/chainer/pull/1218#event-675523798>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AEHFk6nJBMPwc2rokUfay2faYpG18BKPks5qGhPggaJpZM4ImzSy>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Pull request merged**
