### PR TITLE
API: Allow optimizer.setup to accept FunctionSet

### PR DESCRIPTION
**Pull request by sinhrks**
Made ``optimizer.setup`` to accept ``FunctionSet`` itself. I think this simplifies the API and easier to remember.

### CODE REVIEW

**Comment by beam2d** [comment]
I agree with your API change. I have two suggestions:
1. How about making `optimizer.setup` accept an arbitrary object with `parameters` and `gradients` properties?
2. How about making `collect_parameters` return `self` and making it deprecated? It simplifies the implementation and the specification.

**Comment by unnonouno** [comment]
I also agree with this change.
Seiya's idea looks good as a function overloading makes a source confusing.

**Comment by sinhrks** [comment]
Thanks for consideration. Updated based on your suggestions.

**Comment by unnonouno** [comment]
It looks good! Thank you for cool extension.

**Pull request merged**
