### PR TITLE
Stop copying iterators for efficiency

### PR DESCRIPTION
**Pull request by iwiwi**
This PR aims to improve the performance of common use cases with ChainerMN by reducing the frequency of process spawn.

In `Evaluator`, currently iterators are copied for every evaluation time. For most cases, this is not very time consuming. However, we found that this is very slow when we are using `MultiProcessIterator` with `forkserver` or `spawn` modes (c.f., https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods). Therefore, to avoid spawning new processes for each evaluation time, this PR proposes to introduce `reset` method to iterators and use it in `Evaluator`.

### CODE REVIEW

**Comment by iwiwi** [comment]
I talked with Okuta-san, and I was requested to add tests checking `NotImplementedError`

**Comment by iwiwi** [comment]
Added tests for checking `NotImplementedError`

**Comment by okuta** [comment]
LGTM!

**Comment by iwiwi** [comment]
Thanks!! 👏

**Pull request merged**
