### PR TITLE
Catch scikit-cuda ImportError if scikit-cuda is present but CUDA is not

### PR DESCRIPTION
**Pull request by jheymann85**
When importing chainer on a machine where the python installation has scikit-cuda, but CUDA itself is not installed, the ImportError was not handled. This can happen when multiple machines share one python installation but not all of them have a CUDA capable graphic card.

### CODE REVIEW

**Comment by unnonouno** [comment]
Thanks a lot! OK, I understand your situation. Warning is a good idea as it is very strange situation.

Is it possible to store `ImportError` to a variable like `_import_error`, and show it on `init` method?
And please remove redundant commits.

**Comment by jheymann85** [comment]
Done.
But I don't know how to remove the redundant commits from the pull request (sorry, new to github)

**Comment by unnonouno** [comment]
Oh, ok. May I make a new clean branch from your pull request?

If you want to do it yourself:
- This pull request conflicts to the master branch now. First, merge the master branch and fix it.
- `git rebase -i master` and squash all your commits.
- ... or, simply make a new branch from the master branch and re-send a new pull request!!

**Comment by unnonouno** [comment]
I made a simple PR #293

**Comment by unnonouno** [comment]
#293 is merged. So, i'll close this PR. Thanks a lot!

**Pull request closed without merging**
