### PR TITLE
Support multiple integer arrays for cupy.ndarray.__setitem__

### PR DESCRIPTION
**Pull request by yuyu2172**
This PR supports multiple integer arrays for `cupy.ndarray.__setitem__`. I rebased #1928.

I had to change interface of an internal function `_scatter_op_single` to support broader inputs.

After the change,  `_scatter_op_single` supports the input below. Also I left a comment in the code.
```
a.shape= (shape_0, ..., shape_{li-1}, shape_li, ..., shpe_ri, ..., shape_{a.ndim-1})
indices:  an integer array indexing axes from axis_li to axis_ri
li: id of the first axis that get indexed
ri: id of the last axis that get indexed
```
For example, when working on `a[[1,0], [0, 1]], a.shape=(2, 3, 4)`, you have `li=0, ri=1, indices=[3, 1]`.

Originally, `_scatter_op_single` only supported the special case of `li=ri`. In that case, I had to call `a._reshape` before passing to `_scatter_op_single` when working on multiple array indexing. `cupy.ndarray._reshape` may invoke copy, which is a problem because I need to store values to a view and not to a copy of the original array.

The new `_scatter_op_single` makes it possible to avoid calling `cupy.ndarray._reshape` thus never risking to call copy.

### CODE REVIEW

**Comment by rezoo** [comment]
Good, but it seems that `TestArrayAdvancedIndexingVectorValue` does not cover the case where `'indexes'` contains multiple integer arrays. Is it OK?

**Comment by yuyu2172** [comment]
Thank you for comments.
I added tests to `TestArrayAdvancedIndexingVectorValue`. It was my mistake.
I also added tests on broadcasting of indices to some other test classes.

**Comment by rezoo** [comment]
Thank you! After merging #1928, I would like to continue the review.

**Comment by rezoo** [comment]
I merged #1928 Could you resolve the conflicts?

**Comment by yuyu2172** [comment]
Thanks. I resolved the conflicts.

**Comment by rezoo** [comment]
Thanks. I would like to review.

**Comment by rezoo** [comment]
Thanks to you, now `cupy.ndarray` supported a various kinds of advanced indexing.
The next thing we need is PR; currently there does not exist documents of `__getitem__` and `__setitem__` since sphinx ignores all of the special methods.
It seems better to add them into the document, but what do you think?

**Comment by rezoo** [comment]
Good. LGTM.

**Pull request merged**
