### PR TITLE
Fix a bug in sentiment analysis example when using GPU

### PR DESCRIPTION
**Pull request by y-tag**
When GPU is used, `y.data` is `chainer.cuda.gpuarray.GPUArray`.
So, an error is occurred: `AttributeError: 'GPUArray' object has no attribute 'argmax'`

This modification is somewhat ugly...
Is there more sophisticated way?

### CODE REVIEW

**Comment by unnonouno** [comment]
Thank you very much!!! I'll check it.

**Comment by unnonouno** [comment]
Please use `to_cpu` method which converts `GPUArray` to `numpy.ndarray`, and ignores `numpy.ndarray`:
```
cuda.to_cpu(y.data).argmax(1) 
```

**Comment by y-tag** [comment]
:cool:

**Comment by unnonouno** [comment]
Thank you very much!! It works well.

**Pull request merged**
