### PR TITLE
Support dot operation for empty matrices

### PR DESCRIPTION
**Pull request by unnonouno**
NumPy support dot operation between zero-size and non-zero-size matrices, but CuPy doesn't. I fixed it and add a test for it.

### CODE REVIEW

**Comment by delta2323** [comment]
As Numpy also supports the dot operations with two zero-sized matrices. So, please add parameterized test cases for `shape = ((0, 0), (0, 0))`

**Comment by delta2323** [comment]
```
In [6]: a = cupy.testing.shaped_arange((0, 0), numpy, numpy.int32)
In [8]: numpy.dot(a, a)
Out[8]: array([], shape=(0, 0), dtype=int32)
```

**Comment by unnonouno** [comment]
Oh, this is another bug. The current dot implementation doesn't work when the axis dot operator calculates is zero. e.g. `ones((3, 0)).dot(ones.((0, 3)))` doesn't work.

**Comment by unnonouno** [comment]
I'll send another pr about the problem as it is a little complex.

**Comment by delta2323** [comment]
OK, then I will merge this PR.

**Pull request merged**
