### PR TITLE
[WIP] Light-weight typecheck

### LINKED ISSUE #1437: Lightweight type-check
The current type check mechanism is heavy because it creates syntactic tree with Python. It can be bottleneck. We need simpler method to check types of input variables.

### PR DESCRIPTION
**Pull request by unnonouno**
I made a simplified version of type-check. It breaks compatibility. We can make another interface for this feature.

fix #1437

### CODE REVIEW

**Comment by unnonouno** [comment]
I tried to check performance of light-weight typecheck using ptb example. 

- Old version: 2.87 iter/sec
- New version: 3.27 iter/sec
- Without typecheck: 3.30 iter/sec

New version of typecheck looks fast enough.

**Comment by okuta** [comment]
Is this PR still working?

**Comment by unnonouno** [comment]
We need to discuss new design. I have two ideas to make type check faster. This pr is one of them. The other is lazy calculation.

**Comment by okuta** [comment]
OK, I understood.

**Comment by unnonouno** [comment]
I'll close this branch PR #2136 is enough fast and has more compatible to the original than this PR.

**Pull request closed without merging**
