### PR TITLE
Fix async to cpu

### PR DESCRIPTION
**Pull request by iwiwi**
This PR fixes the problem that `cupy.ndarray.get` or `cuda.to_gpu` fails when we give `stream` parameter. I worked with @okuta san.

### CODE REVIEW

**Comment by okuta** [comment]
Thank you.

Please fix bug in below tests.
https://github.com/pfnet/chainer/blob/ed8ef4786be325899119c3827febc9286da7e354/tests/cupy_tests/core_tests/test_ndarray_get.py#L39
https://github.com/pfnet/chainer/blob/ed8ef4786be325899119c3827febc9286da7e354/tests/cupy_tests/core_tests/test_ndarray_get.py#L45

**Comment by iwiwi** [comment]
Fixed. I also fixed a potential bug with regard to async streaming.

**Comment by okuta** [comment]
LGTM!

**Comment by iwiwi** [comment]
Thank you for supporting my first PR!

**Pull request merged**
