### PR TITLE
AbsoluteError (v2)

### PR DESCRIPTION
**Pull request by Hakuyume**
`MeanAbsoluteError` without reduction. The function is renamed to `AbsoluteError`. This PR is related to #2558.

### CODE REVIEW

**Comment by delta2323** [comment]
Review comments are basically same as #2562. So, could you refer that PR?

**Comment by delta2323** [comment]
I am running GPU tests.

**Comment by Hakuyume** [comment]
In #2562, you mentioned not to remove `MeanSquaredError` (https://github.com/pfnet/chainer/pull/2562#issuecomment-294409316). Do I need restore `MeanAbsoluteError` in the same manner?

**Comment by delta2323** [comment]
> Do I need restore MeanAbsoluteError in the same manner?

Sorry for late response. Yes, could you do it?

**Comment by Hakuyume** [comment]
I restored `MeanAbsoluteError`. Please review it.

**Comment by Hakuyume** [comment]
According to a discussion in https://github.com/pfnet/chainer/pull/2562#issuecomment-298460342, this PR may be finished.

**Comment by delta2323** [comment]
Basically we treat this PR in the same as #2562.

`AbsoluteError`, which is implemented by #2567 , will be available in v1.24.0 and v.1.24.0 will be merged to v2 after its release. As this PR is identical to #2567, we need not to merge this PR to v2. We can close this PR and wait v1.24.0 to be merged to v2.

Thank you for your corporation.

**Comment by delta2323** [comment]
Following the tentative conclusion I wrote [here](https://github.com/pfnet/chainer/issues/2558#issuecomment-300378788), I close this PR. Thank you.

**Pull request closed without merging**
