### PR TITLE
Fix type check

### PR DESCRIPTION
**Pull request by beam2d**
I fixed existing type check of functions. It includes following changes:

1. Split type_check.expect calls for ndim checking and shape checking, since, if the ndim is too small, the corresponding shape accessing is failed outside of the type checking utility, which ends up with unfriendly messages.
2. I fixed the type specification of Linear function, which must accept arrays with more than two dimensions. It enables us to directly input to Linear function an array with spatial dimensions.

### CODE REVIEW

**Comment by unnonouno** [comment]
Can you add test for the case for more than two dimensions?

**Comment by delta2323** [comment]
It is better to check if `examples` run properly.

**Comment by unnonouno** [comment]
Fix the test https://github.com/pfnet/chainer-test/blob/master/test_example.sh

**Comment by delta2323** [comment]
:+1:

**Comment by beam2d** [comment]
I added tests to test_linear.py for inputs with more than two dimensions.

**Comment by unnonouno** [comment]
LGTM

**Comment by unnonouno** [comment]
And, I'll make lazy-evaluation mechanism for the problem 1.

**Comment by beam2d** [comment]
Good, that will make the type checking code smarter.

**Pull request merged**
