### PR TITLE
Fix error on reverse indexing empty dimension

### LINKED ISSUE #2695: Reverse indexing on an empty array fails
Reported by @kiyukuta (Thank you!).

Indexing an empty array with a reversing slice will fail:

```
>>> numpy.array([])[::-1]
array([], dtype=float64)
>>> cupy.array([])[::-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1238, in cupy.core.core.ndarray.__getitem__ (cupy/core/core.cpp:27697)
  File "cupy/cuda/memory.pyx", line 104, in cupy.cuda.memory.MemoryPointer.__add__ (cupy/cuda/memory.cpp:2912)
  File "cupy/cuda/memory.pyx", line 88, in cupy.cuda.memory.MemoryPointer.__init__ (cupy/cuda/memory.cpp:2668)
OverflowError: can't convert negative value to size_t
```

`cupy.flip` will fail as well.

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #2695.

### CODE REVIEW

**Comment by unnonouno** [comment]
When the size is zero, memory object behaves differently and it doesn't allocate memory. https://github.com/pfnet/chainer/blob/master/cupy/cuda/memory.pyx#L33 So, how about insert `if` clause to change behavior?

**Comment by niboshi** [comment]
Thank you for the comment.
Can you provide a particular example where `if` clause is needed?
Maybe I don't understand the problem completely, but I feel that's another issue and it should be a separate PR.

**Comment by niboshi** [comment]
Ah, did you mean we should branch earlier and perform completely different operation if `size == 0`, rather than the fix I committed?
I think if we do so, it would become difficult to do the same checks (the number of indices, index bounds, type checks, etc) as `size > 0` cases.

**Comment by unnonouno** [comment]
Ah, I simply think to fix L1238 like this:
```
if v.data == 0:
  v.data = 0
else:
  v.data = self.data + offset
```

**Comment by niboshi** [comment]
OK, I understand.
I agree that any non-zero `offset` should not be added if `v.data` refers to an invalid pointer.
But I think it would be better to fix the computation so that `offset` will always be `0` when `v` is zero-sized, because, with your suggested fix, the computation of `offset` would be meaningless, which is not good for code soundness.

By the way, fixing the `offset` computation can require some more effort. So it would be an option to merge this first and raise a separate issue. (I think this is not directly associated with the original issue anyway.)

**Comment by unnonouno** [comment]
OK, i agree with you. So please write a comment about this fix. It is enough to write that `offset` is negative when an array has no element.

**Comment by niboshi** [comment]
OK.
However, I believe `offset` will never be negative after applying this fix.
I wrote a comment which I think is more accurate.

**Comment by unnonouno** [comment]
OK, it sounds good!

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
