### PR TITLE
fix logsoftmax math

### PR DESCRIPTION
**Pull request by fukatani**
I think the math equations here is corrupted.

### CODE REVIEW

**Comment by fukatani** [comment]
In addition, it is somewhat confusing that the definition of argument `x` is different with between explanation of `softmax` and `logsoftmax`. 
In `logsoftmax`, `x` is input array, but in `softmax`, `f(x)` is input array.

**Comment by rezoo** [comment]
I agree that the current document makes no sense, and wrote the draft. How about the following?

    This function computes its logarithm of softmax along the second axis. Let
    :math:`x = (x_1, x_2, \\dots, x_d)^{\\top}` be the d dimensional index
    array and :math:`f(x_1, \\dots, x_d)` be the corresponding input array.
    For each index :math:`x` in the input array, it computes the logarithm
    of the probability :math:`\log p(x)` defined as

    .. math::
        p(x) = {\\exp(f(x_1, x_2, \\dots, x_d)) \\over \\sum_{x'_2} \\exp(f(x_1, x'_2, \\dots, x_d))}.

    This method is theoretically equivalent to ``log(softmax(x))`` but is more
    stable.

I think the 2nd equation is no needed.

**Comment by fukatani** [comment]
I agree with you.
2nd equation is redundant.

**Comment by rezoo** [comment]
Thank you! I would like to merge this one.

**Pull request merged**
