### PR TITLE
Fix SGD to use same code for CPU and GPU

### PR DESCRIPTION
**Pull request by delta2323**
We do not have to separate CPU and GPU case in the implementation of SGD.

### CODE REVIEW

**Comment by gwtnb** [comment]
LGTM

**Comment by gwtnb** [comment]
Please fix for flake8

**Comment by unnonouno** [comment]
The original GPU code uses only one kernel, and is faster.

**Comment by delta2323** [comment]
CuPy is so made that it enables us to unify CPU code and GPU code. So I first thought it is somewhat self-contradictory that we separately write CPU and GPU codes even though we can unify them. But I come to think that this feature of CuPy is for users who would like to enhance readability. As SGD is often used, we should put a high priority on its speed, need not to enhance readability at the cost of speed.

**Pull request closed without merging**
