### PR TITLE
Adds Subpixel Depth2Space and Space2Depth Functionality.

### PR DESCRIPTION
**Pull request by tjtorres**
This adds some new functionality to take stacked outputs from a convolution
and then intersperse them to create an upscaled array (Depth2Space).

It also adds the inverse operation (Space2Depth) for the purpose of building symmetrical
architectures for subpixel autoencoders etc.

Details of the algorithm's underpinnings can be found at https://arxiv.org/abs/1609.05158

### CODE REVIEW

**Comment by delta2323** [comment]
Thank you for sending the PR! It seems Depth2Space and Space2Depth are independent, except that they are in the same module. So, is it possible to divide this PR into two smaller PRs so that we can narrow the scope of review? Thank you for your corporation.

**Comment by tjtorres** [comment]
Sure, I will submit them as separate PRs. Thanks.

**Comment by delta2323** [comment]
Thanks. Then, I will close this PR when you send the PRs.

**Comment by tjtorres** [comment]
Ok added PRs #1748 and #1749 splitting this PR into its component halves.

**Pull request closed without merging**
