### PR TITLE
TST: Made tests executable

### PR DESCRIPTION
**Pull request by sinhrks**
For convenient unit testing.

### CODE REVIEW

**Comment by unnonouno** [comment]
How about 
```
nosetests tests/path/to/test.py
```
?

**Comment by sinhrks** [comment]
The point is we can run the test via ``__main__`` from the editor immediately without console. I understand the soln is quite common.

https://github.com/search?q=nose.runmodule&type=Code&utf8=%E2%9C%93

**Comment by unnonouno** [comment]
OK, I understand your goal.
Can you make a utility method to run test easily in `chainer.testing` module like this? :
```
testing.run_test(__main__, __file__)
```

I will add a command to travis config to check whether all test scripts correctly have the line like
```
grep "testing.run_test(__main__, __file__)" xxx_test.py
```

**Comment by sinhrks** [comment]
OK. I think we can't use ``run_test`` because it is targetted as test case by ``nose``. How about ``run_module``?

**Comment by unnonouno** [comment]
Great!! I agree with you.
And, please import `nose` at the top of the source.
https://www.python.org/dev/peps/pep-0008/#imports

**Comment by sinhrks** [comment]
Sure. Pls lmk if any others.

**Comment by unnonouno** [comment]
OK! Thank you for your great patch and many discussion!!

**Pull request merged**
