### PR TITLE
fix bug in roi pooling forwarding with cpu

### PR DESCRIPTION
**Pull request by apple2373**
I implemented fast r-cnn https://github.com/apple2373/chainer-simple-fast-rnn, and realized roi pooling with cpu does not work. It always outputs only one roi when forwarding. I just copied two lines from GPU implementation. Also I am not sure backward function is also wrong or not because I only use forwarding now.

### CODE REVIEW

**Comment by okuta** [comment]
Thank you for your PR.
Would you write the test?

**Comment by apple2373** [comment]
Unfortunately I am not familiar with software testing or software engineering. It seems that roi pooling already has the test: https://github.com/apple2373/chainer/blob/c4b5082e3b0d2973152022aecefb07486b806f5e/tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py

 I want to ask inputs from @wkentaro who is the developer. I guess this is the easy mistake to understand for him.

**Comment by wkentaro** [comment]
The code looks good to me.
But I'm not sure how to test this.. the `test_roi_pooling_2d.py` already has `test_forward_cpu_gpu_equal` and it passed unexpectedly..

**Comment by mitmul** [comment]
@apple2373 As for the test, how about modifying this line from N = 4 to N = 3 here?: [pooling_tests/test_roi_pooling_2d.py#L17](https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py#L17)
The number of images in a minibatch and number of rois are incidentally same. That's why the test was passed I think, so please consider to try this modification.

**Comment by t-abe** [comment]
mitmul's idea looks good for testing this PR.
@apple2373 Could you modify the test as he mentioned?

**Comment by apple2373** [comment]
I really do not know about software testing. Is it ok just to modify the test_roi_pooling_2d.py as mitmul mentioned, and add it to this PR?

**Comment by t-abe** [comment]
Yes. You can add commits into fix_roi_pooling_cpu branch, then this PR is automatically updated.

**Comment by apple2373** [comment]
I did it.

**Comment by t-abe** [comment]
Added test failed.
Probably we should fix same bug in `backward`.
https://github.com/apple2373/chainer/blob/cbfd52bf0d9b26aa8451c4dbf65d991b2b0ed824/chainer/functions/pooling/roi_pooling_2d.py#L188

**Comment by apple2373** [comment]
I modified cpu backward in the same way.

**Comment by t-abe** [comment]
Thank you.
The test still failed. I am going to check the code.
Could you do it too?
You can run a test by `$ nosetests -v tests/chainer_tests/function_tests/pooling_tests/....py`.

**Comment by apple2373** [comment]
I am not sure what is going on but the test will end up "RuntimeError: CUDA environment is not correctly set up". Maybe test cannot be run only with CPU.  I'll try to run on GPU server later.

**Comment by t-abe** [comment]
You can run only tests only on cpu by giving `-a '!gpu'` option to `nosetests`.

**Comment by apple2373** [comment]
Thank you. I was able to reproduce test failure on my laptop, but I do not think I can fix it because I do not fully understand the implementation.

**Comment by t-abe** [comment]
I fixed the bug and open PR #1352.

**Pull request merged**
