### PR TITLE
Implement cupy.sort again after reverted.

### PR DESCRIPTION
**Pull request by takagi**
`cupy.sort` was once pull requested on #1817, but reverted on #2523 because of some additional fix on handling `CFLAGS`, `LDFLAGS` and `CPPFLAGS` on #2522 .

This PR requests implementing `cupy.sort` again.

### CODE REVIEW

**Comment by unnonouno** [comment]
I have questions about this problem. I sent a PR which applies XFLAGS to nvcc compiler, but i don't know it is adequate.
- Does nvcc supports all arguments for gcc?
- Is it compatible in visual studio?
- Is it possible to use nvcc only for .cu files and to use gcc for other cpp files?

**Comment by takagi** [comment]
> Does nvcc supports all arguments for gcc?

I'm not sure, it might not. http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#nvcc-command-options

Such arguments may need to be passed through `--compiler-options` and `--linker-options` to underlaying gcc or cl.

> Is it compatible in visual studio?

I will ask it to @kmatsuura .

> Is it possible to use nvcc only for .cu files and to use gcc for other cpp files?

It would be possible, actually I first thought of the same way as you mention. A problem of the approach, I think, is that distutils seem to be designed to use only a compiler for any kinds of extension source files so some ad-hoc implementation would be needed to make it switch compilers for different types of source files. Anyway, using nvcc only for .cu files would be still a remaining option.

**Comment by takagi** [comment]
Following is a problem on passing through command line arguments to underlying C++ compilers via `--compiler-options` option. Unfortunately, it causes that we can not pass through a path string which contains spaces.

## Background
Want to pass through the values of environment variables `CFLAGS` and `CPPFLAGS` to underlying C++ compilers via `nvcc`'s `--compiler-options` option.

## Problem
In case those environment variables contain specific characters, it looks no way to properly escape the characters. I tried possible approaches, such as backslash(`\`), hat(`^`; escape character on Windows command prompt), repeating the same character(Visual Basic convention) and multiple escaping, but they made no way.

**Unix**

Character|Expected command generated|nvcc command
---|---|---
Commas|`gcc ... foo,bar ...`|`nvcc ... --compiler-options=foo\\,bar ...`
Spaces|`gcc ... "foo bar" ...`|?
Double quotes|`gcc ... \"foo\" ...`|?

**Windows**

Character|Expected command generated|nvcc command
---|---|---
Commas|`cl.exe ... foo,bar ...`|`nvcc ... --compiler-options="""foo,bar""" ...`
Spaces|`cl.exe ... "foo bar" ...`|?
Double quotes|`cl.exe ... \"foo\" ...`|?

## `--compiler-options` processing algorithm on Windows (guess)
FYI, I show the algorithm, I guess, how nvcc processes the value of its `--compiler-options`option on Windows.

1. The original command line argument.

    ` --compiler-options="""foo,bar"""`

2. Consume the enclosing double quotes at the both ends.

    `""foo,bar""`

3. Unescape repeating double quotes following Visual Basic convention.

    `"foo,bar"`

4. Parse the result with common parsing way with double quote escaping, leaving the comma as it is. (Without escape, the comma would be interpreted as a separator)

    `foo,bar`

**Comment by takagi** [comment]
Talking with @okuta, environment variables such as `CFLAGS` are not needed to pass through `--compiler-options` for compiling CUDA C files, so the comment above, https://github.com/pfnet/chainer/pull/2539#issuecomment-301411799, makes no sense anymore.

I will clean the change of this PR and make it ready to be merged.

**Comment by takagi** [comment]
This PR is now sent to cupy, so I close it. https://github.com/cupy/cupy/pull/55

**Pull request closed without merging**
