### PR TITLE
Fix PlotReport.available and write test

### PR DESCRIPTION
**Pull request by unnonouno**
No argument is required for a static method.

### CODE REVIEW

**Comment by mitmul** [comment]
I confirmed that the below outputs will show up when running tests

without matplotlib:
```
$ nosetests -s chainer_tests/training_tests/extensions_tests/test_plot_report.py
/home/mitmul/chainer/chainer/training/extensions/plot_report.py:24: UserWarning: matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.

  $ pip install matplotlib

  warnings.warn('matplotlib is not installed on your environment, '
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

with matplotlib:
```
$ nosetests -s chainer_tests/training_tests/extensions_tests/test_plot_report.py
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```
(no warnings)

So it's LGTM.

**Comment by unnonouno** [comment]
Yes, but i can check warnings behavior. I'll fix it.

**Comment by unnonouno** [comment]
I updated the test.

**Comment by unnonouno** [comment]
This problem is solved in #2317. So, this pr only contains a test.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
