### PR TITLE
Simplify matmul function

### PR DESCRIPTION
**Pull request by okuta**
This PR uses `cupy.matmul`.
Rel #1794

### CODE REVIEW

**Comment by boeddeker** [comment]
Is it not better to change chainer.matmul to be similar to numpy?

numpy.matmul: shapes:  (..., n, n) * (..., n, n) = (..., n, n)
numpy.dot: shapes:  (n, n) * (n, n) = (n, n)
chainer.matmul: shapes:  (n, n) * (n, n) = (n, n)
chainer.batch_matmul: shapes:  (m, n, n) * (m, n, n) = (m, n, n)

The behavior of chainer.batch_matmul for vectors and matrices (ndim in {1, 2}) is much more strange.

And one further point, in my opinion the operation should be equal to numpy.matmul or raising an exception.

Example code for python 3.5 and numpy > 1.10 with the constraints, no broadcasting and inputs have minimum 2 dims:
```
def xp_hermitian(x):
    xp = cuda.get_array_module(x)
    return xp.swapaxes(x.conj(), -1, -2)

class MatMul(function.Function):
    def check_type_forward(self, in_types):
        type_check.expect(in_types.size() == 2)
        if not in_types[0].value.dtype in (
                numpy.float32, numpy.complex64, numpy.complex128):
            raise TypeError(in_types[0].value.dtype)
        assert in_types[1].value.dtype in (
            numpy.float32, numpy.complex64, numpy.complex128)
        type_check.expect(
            in_types[0].ndim >= 2,
            in_types[1].ndim >= 2,
            in_types[0].shape[:-2] == in_types[1].shape[:-2],
            in_types[0].shape[-1] == in_types[1].shape[-2],
        )
    def forward(self, x):
        xp = cuda.get_array_module(*x)
        result = utils.force_array(x[0] @ x[1])
        return result,

    def backward(self, x, gy):
        grad_x_0_star = utils.force_array(gy[0] @ xp_hermitian(x[1]))
        grad_x_1_star = utils.force_array(xp_hermitian(x[0]) @ gy[0])
        return grad_x_0_star, grad_x_1_star
```

**Comment by okuta** [comment]
Thank you for your advice.
I will fix.

**Comment by okuta** [comment]
@boeddeker I thought about your advice.
I think that it is better to deal with another PR because the interface of matmul is complex (eg transa and transb).
Could you create issue about your proposal?

**Comment by gwtnb** [comment]
LGTM

**Pull request merged**
