### PR TITLE
Rebase of PR #1713: CuPy Fusion for Chainer

### PR DESCRIPTION
**Pull request by niboshi**
Rebased #1713 and did some minor modifications

### CODE REVIEW

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
@niboshi Please rebase

**Comment by niboshi** [comment]
@okuta Rebased. Also, I added a fusion binding of math.rounding.fix function which was the cause of the conflict.

**Comment by okuta** [comment]
Thank you!

**Pull request merged**
