### PR TITLE
Profiler

### LINKED ISSUE #966: Support profiler API
CUDA has profiler API to switch the profiler. I need this API on CuPy to measure performance of part of my code.
http://docs.nvidia.com/cuda/profiler-users-guide/#abstract

### PR DESCRIPTION
**Pull request by unnonouno**
fix #966

### CODE REVIEW

**Comment by okuta** [comment]
Plase write the function call test?

**Comment by unnonouno** [comment]
I wrote a unit test. And, i fixed the method to call `stop` when an error occurs.
Is this file name or something like that OK?

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
Do you write document?
If this PR is finished, I will merge.

**Comment by unnonouno** [comment]
I wrote its document.

**Comment by okuta** [comment]
OK.
Please change `https://github.com/pfnet/chainer/blob/master/docs/source/cupy-reference/cuda.rst`.

**Comment by unnonouno** [comment]
I already fixed it.

**Comment by okuta** [comment]
Sorry, I had missed.

**Pull request merged**
