### PR TITLE
Add support of flipud() and fliplr()

### PR DESCRIPTION
**Pull request by tsuchm**
This pull request contains 4 features.

1. Implementation of cupy.flipud() which works same as numpy.flipud()
2. Implementation of cupy.fliplr()  which works same as numpy.fliplr()
3. Implementation of Functions.FlipUD which is a wrapper of cupy.flipud()
4. Implementation of Functions.FlipLR which is a wrapper of cupy.fliplr()

Because I am a novice programmer of matrix manipulation, my implementation may be quite slow, but I required it for my model.  I hope someone will improve them.

### CODE REVIEW

**Comment by okuta** [comment]
Thank you for your PR. These functionality is good.

Please add tests.

**Comment by unnonouno** [comment]
@tsuchm do you have time to make test? If no, i'll fix it.

**Comment by tsuchm** [comment]
Sorry, I have no time to check testing framework.

**Comment by unnonouno** [comment]
OK. I'll make it. And thank you for contribution!

**Comment by okuta** [comment]
#2239 is merged!
Thank you @tsuchm

**Pull request closed without merging**
