### PR TITLE
Fix the shuffle timing to always re-shuffle after an epoch #1416

### LINKED ISSUE #1416: SerialIterator's shuffle does not work under certain batch sizes
When we give `shuffle=True` to `SerialIterator`, re-shuffling after an epoch is skipped if `len(dataset)` is divisible by `batch_size`.

image

https://github.com/pfnet/chainer/blob/master/chainer/iterators/serial_iterator.py#L65

Variable `_order` is never re-shuffled if `rest` > 0 (i.e., `len(dataset)` is divisible by `batch_size`).

(If it is okay, I'm interested in working on this issue at the development meeting tomorrow.)

### PR DESCRIPTION
**Pull request by iwiwi**
This PR fixes #1416

### CODE REVIEW

**Comment by zori** [comment]
LGTM. Thank you for the fix!

**Comment by unnonouno** [comment]
Can you write a test for this patch? Please check if data is shuffled in each epoch.

**Comment by iwiwi** [comment]
Thank you for your feedback. I wrote easy tests. If necessary, more thorough tests are possible. I also added the same tests to MultiprocessIterator.

**Comment by unnonouno** [comment]
Thank you! It looks enough. LGTM

**Pull request merged**
