### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by unnonouno**
I fixed typo

### CODE REVIEW

**Comment by delta2323** [comment]
Didn't the test run this code path? I would like to confirm the test certainly effective.

**Comment by unnonouno** [comment]
You can confirm that the original code cannot be passed with cuDNN v3.

**Comment by okuta** [comment]
I checked.
LGTM!

**Comment by delta2323** [comment]
> You can confirm that the original code cannot be passed with cuDNN v3.

I see. Thanks.

**Pull request merged**
