### PR TITLE
Remove chainer.functions.caffe.CaffeFunction

### LINKED ISSUE #2322: Remove chainer.functions.caffe.CaffeFunction
This is left for backward compatibility.

### PR DESCRIPTION
**Pull request by delta2323**
Fix #2322

### CODE REVIEW

**Comment by gwtnb** [comment]
Please remove this line. https://github.com/pfnet/chainer/blob/ec5804abb43e110e9d4a925de3a9d3b2948923b7/setup.py#L29

**Comment by delta2323** [comment]
Thank you. I removed it.

**Comment by unnonouno** [comment]
Rebase _v2

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
