### PR TITLE
Support cover_all=True in Convolutional2D

### PR DESCRIPTION
**Pull request by wkentaro**
- [x] Fix test for cover_all=True with use_cudnn=True

Currently this has error for cudnn function:

```
======================================================================
FAIL: test_backward_gpu_nobias (test_convolution_2d.TestConvolution2DFunction_param_2)  parameter: {'c_contiguous': False, 'cover_all': True}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wkentaro/chainer/chainer/testing/condition.py", line 71, in wrapper
    fail()
  File "/home/wkentaro/chainer/chainer/testing/condition.py", line 51, in fail
    instance.fail(msg)
AssertionError:
Fail: 3, Success: 0

The first error message:
Traceback (most recent call last):
  File "/home/wkentaro/chainer/chainer/testing/condition.py", line 57, in <lambda>
    lambda: f(*args, **kwargs),
  File "/home/wkentaro/chainer/tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py", line 122, in test_backward_gpu_nobias
    None, cuda.to_gpu(self.gy))
  File "/home/wkentaro/chainer/tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py", line 102, in check_backward
    args, y_grad, eps=1e-2)
  File "/home/wkentaro/chainer/chainer/gradient_check.py", line 196, in check_backward
    y = func(*xs)
  File "/home/wkentaro/chainer/chainer/function.py", line 105, in __call__
    outputs = self.forward(in_data)
  File "/home/wkentaro/chainer/chainer/function.py", line 181, in forward
    return self.forward_gpu(inputs)
  File "/home/wkentaro/chainer/chainer/functions/connection/convolution_2d.py", line 111, in forward_gpu
    y_desc.value, y.data.ptr)
  File "cupy/cuda/cudnn.pyx", line 347, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:4771)
    cpdef convolutionForward(
  File "cupy/cuda/cudnn.pyx", line 359, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:4577)
    check_status(status)
  File "cupy/cuda/cudnn.pyx", line 167, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1311)
    raise CuDNNError(status)
CuDNNError: CUDNN_STATUS_BAD_PARAM: CUDNN_STATUS_BAD_PARAM
```

### CODE REVIEW

**Comment by wkentaro** [comment]
Could you please give me any advice to fix the cudnn error?
I worked around for a while, and have no idea why this raises..

**Comment by delta2323** [comment]
Which cuDNN version do you use? Could you check `CUDNN_VERSION` in `cudnn.h` and version number `libcudnn` (i.e. x, y and z in `libcudnn.so.x.y.z`).

**Comment by wkentaro** [comment]
`CUDNN_VERSION` is `3007`.
I have `libcudnn.so.7.0.64`.

**Comment by delta2323** [comment]
Thank you for sharing the information. We confirmed that the version of `cudnn.h` and `libcudnn.so` is consistent.

**Comment by wkentaro** [comment]
The test passed. Could you please review?

**Comment by delta2323** [comment]
Thank you for your implementation. I will review it.

**Comment by delta2323** [comment]
LGTM. We will merge this PR in the next minor release.

**Pull request merged**
