### PR TITLE
Improve sigmoid_cross_entropy

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by unnonouno** [comment]
Do you have a  script to check efficiency?

**Comment by okuta** [comment]
I think that hard to check.
This PR includes the deletion of synchronization .
https://github.com/pfnet/chainer/pull/898/files#diff-783b42248bd19bcd63b880b723ec0357R35

**Comment by unnonouno** [comment]
This patch improve performance about 30%.
This is my test code and its result on my GTX970 environment.

```
% cat test_sigmoid.py
import chainer
import cupy

x = chainer.Variable(cupy.zeros((1000, 1000), cupy.float32))
y = chainer.Variable(cupy.zeros((1000, 1000), cupy.int32))

for i in range(1000):
    chainer.functions.sigmoid_cross_entropy(x, y)
```

improved:
```
% time python test_sigmoid.py
python test_sigmoid.py  1.54s user 1.04s system 95% cpu 2.707 total
```

original:
```
% time python test_sigmoid.py
python test_sigmoid.py  2.25s user 0.52s system 99% cpu 2.769 total
```

**Comment by okuta** [comment]
Thank you for the benchmark!

**Comment by unnonouno** [comment]
LGTM!

**Pull request merged**
