### PR TITLE
Implement logarithm function to the base ten, common logarithm.

### PR DESCRIPTION
**Pull request by takagi**
This PR implements logarithm to the base ten, `log10`, function. Rel #1508 .

Now it has only tests for FP32, tests for FP16 and FP64 would be added as another issue.

It also has a bit boring test code with repeated lines, I think of providing abstraction for lifting basic numpy/cupy functions to Chainer functions later. I would be another issue.

### CODE REVIEW

**Comment by takagi** [comment]
I've added tests for FP16 and FP64.

**Comment by bkvogel** [comment]
This looks good, but I see that your #1508 also has log2. Do you intend this PR to replace that one?

**Comment by takagi** [comment]
No, it looks so is because log10 branch branches off log2 branch and this PR is compared to master, so the commit list includes log2 branch's commits as well as log10 branch's. Please leave them as they are, merging log2 branch makes all clear.

**Comment by bkvogel** [comment]
I see. Thanks for the clarification.

**Comment by bkvogel** [comment]
LGTM!

**Comment by takagi** [comment]
Thanks!

**Pull request merged**
