### PR TITLE
Add document about functions of cuDNN workspace

### PR DESCRIPTION
**Pull request by okuta**
Please see also #1122

### CODE REVIEW

**Comment by unnonouno** [comment]
Do you have a link to a detailed description of the workspace size?

**Comment by okuta** [comment]
It is wrote in pdf of cuDNN SDK.

**Comment by unnonouno** [comment]
So, please write something like this: 'Check "cuDNN Library User Guide" for detail.'

**Comment by beam2d** [comment]
LGTM!

**Pull request merged**
