### PR TITLE
Fix ResNet50 in examples/imagenet

### PR DESCRIPTION
**Pull request by mitmul**
Somehow this commit ( https://github.com/pfnet/chainer/pull/2644/commits/2c7affce0db397a3f426a1e5204749a2134e058b ) hasn't been merged.

### CODE REVIEW

**Comment by beam2d** [comment]
https://github.com/pfnet/chainer/blob/_v2/examples/imagenet/resnet50.py#L15 Do you mean this line? It looks correctly merged to me.

**Comment by mitmul** [comment]
@beam2d Oh, this change is not what I intended. I wanted to apply this change (removing nobias=True) at [L89](https://github.com/pfnet/chainer/blob/_v2/examples/imagenet/resnet50.py#L89)...

**Comment by mitmul** [comment]
I fixed the wrong modification at L:16 also

**Comment by beam2d** [comment]
Oh, I see. I have understood the change.

**Pull request merged**
