### PR TITLE
Add Parameter

### PR DESCRIPTION
**Pull request by beam2d**
This PR is a part of #1970. In order to distinguish a parameter variable from a non-parameter variable without relying on explicit `add_param` call, I wrote a subclass of `Variable` named `Parameter` (a design similar to PyTorch). I think this is a good timing, so I also refactored the code and move features of `Variable` specific to parameters to `Parameter`. It makes the implementation and API of `Variable` much simpler.

I will work on #1970 using this Parameter class. Any comments are welcome.

### CODE REVIEW

**Comment by beam2d** [comment]
I found that I mistakenly added changes to the Parameter in #2657. Maybe it is better to directly review the Parameter part in #2657 as well.

**Comment by delta2323** [comment]
Do we need this PR if we adopt `Link.init_scope()` and `Link.forward_scope()` suggested in #2657?

**Comment by delta2323** [comment]
Could you close this PR if it is not needed.

**Comment by beam2d** [comment]
This change is included in #2657 and that one is more advanced than this PR, so I'll close this PR.

**Pull request closed without merging**
