### PR TITLE
Fix cuda build on macOS

### LINKED ISSUE #1700: Can't install Chainer with CUDA on Mac
I tried to install Chainer with CUDA on Mac, but following errors were occurred.
How do I deal with followings, and install Chainer with CUDA?

[Environment]
- HW: MacBook Pro(Mid 2010) with NVIDIA GeForce 320M 256MB
- OS: OS X El Capitan(10.11.6)
- CUDA: CUDA 7.5
- Python: Python 2.7.12 |Anaconda 4.1.1 (x86_64)
- .bash_profile
  - export PATH="/Developer/NVIDIA/CUDA-7.5/bin:$PATH"                                                                                                                                                     
  - export LD_LIBRARY_PATH="/Developer/NVIDIA/CUDA-7.5/lib:/usr/local/cuda/lib/:$LD_LIBRARY_PATH"                                                                                                          
  - export CPATH="/Developer/NVIDIA/CUDA-7.5/include:$CPATH"                                                                                                                                               
  - export CUDA_INC_DIR="/Developer/NVIDIA/CUDA-7.5/bin:$CUDA_INC_DIR"                                                                                                                                     
  - export DYLD_LIBRARY_PATH="/usr/local/cuda/lib:$DYLD_LIBRARY_PATH"                                                                                                                               
- Chainer:1.16.0

[Error Message]
> pip install chainer --no-cache-dir -vvvv

    gcc -fno-strict-aliasing -I/Users/****/.pyenv/versions/anaconda2-4.0.0/envs/chainer/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda/include -I/Users/****/.pyenv/versions/anaconda2-4.0.0/envs/chainer/include/python2.7 -c cupy/cuda/cublas.cpp -o build/temp.macosx-10.6-x86_64-2.7/cupy/cuda/cublas.o
    In file included from cupy/cuda/cublas.cpp:272:
    cupy/cuda/cupy_cuda.h:18:26: error: typedef redefinition with different types ('cublasDataType_t' vs 'enum cudaDataType_t')
    typedef cublasDataType_t cudaDataType;
                             ^
    /usr/local/cuda/include/library_types.h:66:3: note: previous definition is here
    } cudaDataType;
      ^
    cupy/cuda/cublas.cpp:5650:20: error: no matching function for call to 'cublasSgemmEx'
      __pyx_v_status = cublasSgemmEx(((cublasHandle_t)__pyx_v_handle), ((cublasOperation_t)__pyx_v_transa), ((cublasOperation_t)__pyx_v_transb), __pyx_v_m, __pyx_v_n, __pyx_v_k, (&__pyx_v_alpha), ((void const *)__pyx_v_A), ((cudaDataType)__pyx_v_Atype), __pyx_v_lda, ((void const *)__pyx_v_B), ((cudaDataType)__pyx_v_Btype), __pyx_v_ldb, (&__pyx_v_beta), ((void *)__pyx_v_C), ((cudaDataType)__pyx_v_Ctype), __pyx_v_ldc);
                       ^~~~~~~~~~~~~
    /usr/local/cuda/include/cublas_api.h:1587:39: note: candidate function not viable: no known conversion from 'cudaDataType' (aka 'cudaDataType_t') to 'cublasDataType_t' for 9th argument
    CUBLASAPI cublasStatus_t CUBLASWINAPI cublasSgemmEx  (cublasHandle_t handle,
                                          ^
    2 errors generated.
    error: command 'gcc' failed with exit status 1

### PR DESCRIPTION
**Pull request by wkentaro**
Close #1700

### CODE REVIEW

**Comment by unnonouno** [comment]
`library_types.h` is required for cuda 8.
I investigated the problem in detail.
- cuda 7.5.20 only defines cublasDataType_t and does not have `library_types.h`. So, typedef of cudaDataType_t works correctly.
- cuda 7.5.27 defines both cublasDataType_t and cudaDataType_t and has `library_types.h`, and no header file use cudaDataType_t.
- cuda 8.0.x defines cudaDataType_t, and cublasDataType_t is typedef of cudaDataType_t for backward compatibility.

Please check cuda version, and disable the include only when the version is 7.5.

**Comment by wkentaro** [comment]
Thank you for the investigation.
In my environment, the cuda version was 7.5.26 and it has `library_types.h`.

**Comment by unnonouno** [comment]
LGTM. Btw, currently the setup script cannot build chainer on mac. I'll check it.

**Comment by wkentaro** [comment]
Thank you.

**Comment by Hornobster** [comment]
Maybe I'm missing something, but this args variable seems like is never used.
https://github.com/pfnet/chainer/blob/a973c71ee1d5e1adc408e3c0582a4a23e3c0c5b5/chainer_setup_build.py#L106-L112

**Comment by unnonouno** [comment]
setdefault returns reference to a list. So, `append` method correctly change extra_link_arg.

**Comment by Hornobster** [comment]
Ok, thank you. I'm trying to understand why the install script still doesn't work.
I'm on OSX El Capitan with CUDA 7.5, and the paths are correct:

....
Include directories: ['/Developer/NVIDIA/CUDA-7.5/include']
Library directories: ['/Developer/NVIDIA/CUDA-7.5/lib', '/usr/local/cuda/lib']
dyld: Library not loaded: @rpath/libcublas.7.5.dylib
  Referenced from: /tmp/tmp0NG7V3/a
  Reason: image not found
**************************************************
*** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand', 'nvToolsExt']
*** WARNING: Skip installing cuda support
*** WARNING: Check your LDFLAGS environment variable
**************************************************
....

I'll let you know.

**Comment by unnonouno** [comment]
Oh, sorry. This is the problem i'm now facing since yesterday. I found `-F/Library/Frameworks -framework CUDA` option for the linker solve this problem. But, i didn't confirmed if this fix is correct because i'm not familiar with Mac development environment.

**Comment by Hornobster** [comment]
I had a couple of file permissions problems; fixing those solved the problem and chainer compiles and installs correctly.
Unfortunately, I have to solve a CUDA related problem: apparently nvcc doesn't support the new Apple LLVM v8.0.0, so I'll have to downgrade to Xcode 7.3.
I don't think we can do anything about that though.

**Pull request merged**
