### PR TITLE
Support numpy like to-string function for variable.

### PR DESCRIPTION
**Pull request by fukatani**
This PR breaks backward compatibility.

Numpy like repr function is useful for console debugging.

ex.
```
>>> a = numpy.array([1., 2.])
>>> a
array([ 1.,  2.])
>>> v = Variable(a)
>>> v
variable([ 1.,  2.])
>>> v = Variable(a, name='x')
>>> v
variable x([ 1.,  2.])
```

I also implemented __str__ function.
ex.
```
>>> a = numpy.array([1., 2.])
>>> print(a)
[ 1.  2.]
>>> v = Variable(a)
>>> print(v)
variable([ 1.  2.])
>>> v = Variable(a, name='x')
>>> print(v)
variable x([ 1.  2.])
```

### CODE REVIEW

**Comment by mitmul** [comment]
Thank you for sending this PR! It's useful PR and LGTM, but I'm thinking how we should deal with the backward compatibility break. Then, how about merging this to Chainer v2?
@beam2d,  Do you have any comments?

**Comment by fukatani** [comment]
Merging to v2 is acceptable for me.

**Comment by beam2d** [comment]
I think it's better to merge it to v2. IMHO, how a variable is printed can be treated as an implementation detail, but it does not mean this change won't break any existing code.

**Comment by fukatani** [comment]
Thank you for your comments.
I close this PR and reopen to send merge request to _v2.

**Pull request closed without merging**
