### PR TITLE
Improve col2im and im2col

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by rezoo** [comment]
I assume that it does simplify the code, but its computational cost is almost the same. Is it right?

**Comment by okuta** [comment]
Yes, almost the same.
But the computational cost is not same in `col2im_gpu` with dilation mode.

**Comment by rezoo** [comment]
Ok I understand. In the case of dilated convolution, the previous one is not efficient, whereas the proposed one efficiently handles such case.

**Comment by rezoo** [comment]
Reading the PR, I conclude that there does not any crucial problems.

**Comment by gwtnb** [comment]
LGTM

**Comment by rezoo** [comment]
Thank you! then I would like to merge this.

**Pull request merged**
