### PR TITLE
Support boolean array for cupy.ndarray.__setitem__

### PR DESCRIPTION
**Pull request by yuyu2172**
This PR supports boolean array for `cupy.ndarray.__setitem__`.

+ It supports boolean array indexing on axes (e.g. `a[:, np.array([True, False])]`).
+ It does not support combination of boolean arrays (e.g. `a[np.array([True, False]), np.array([False, True])]`).

Also, I changed name of internal function `_boolean_array_indexing` which was used for boolean array indexing of `__getitem__` to `_getitem_mask`. I did so because the name was vague, and it needed to be distinguishable from functions for `__setitem__`.

### CODE REVIEW

**Comment by rezoo** [comment]
Thank you! After reading the code, I concluded that there is no problem to merge this PR.
@okuta Could you briefly read the code and confirm that there is no problem? Just in case.

**Comment by yuyu2172** [comment]
I restarted CI.

**Comment by yuyu2172** [comment]
@rezoo 
I found the current implementation to fail in the case when `value` can not be broadcasted to `a`'s shape.
The failing cases are illustrated in 27cad5.

I fixed the code to work in those cases, so could you check it?

**Comment by rezoo** [comment]
Good. Then I'll check this one.

**Comment by rezoo** [comment]
Good. For computational efficiency this PR uses the two `scan` operators, and I think it is a good choice in the field of GPU community. LGTM.

**Pull request merged**
