### PR TITLE
Remove deprecated functions in chainer.cuda module

### LINKED ISSUE #2016: Remove deprecated cuda module functions
There are many deprecated functions in chainer.cuda module, which were originally used for unified interface for numpy and pycuda. They can be removed in v2.

### PR DESCRIPTION
**Pull request by delta2323**
Fix #2016

### CODE REVIEW

**Comment by beam2d** [comment]
Could you make the PR title more accurate?

**Comment by delta2323** [comment]
OK, I changed the PR title.

**Comment by beam2d** [comment]
The change looks good. Could you remove the corresponding document?

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
