### PR TITLE
Fix Convolution2D.backward_gpu so that it does not use cuda.linalg

### PR DESCRIPTION
**Pull request by delta2323**
When CuDNN is not used, `Convolution2D.backward_gpu` uses `cuda.linalg`, which is no longer available after CuPy is introduced. This PR removes dependency on `cuda.linalg.dot` and `cuda.linalg.add_dot` and uses `cuda.cupy.dot` instead.

### CODE REVIEW

**Comment by beam2d** [comment]
We should fix the test code to pass the im2col/col2im path even in cuDNN-enabled environments.

**Comment by beam2d** [comment]
I fixed tests to check im2col version even if cuDNN is enabled.

**Comment by delta2323** [comment]
As for @beam2d's fix, it looks good for me.

**Comment by beam2d** [comment]
OK, then I'll merge.

**Comment by beam2d** [comment]
Thank you!

**Pull request merged**
