### PR TITLE
Fix setup problem with numpy 1.11b3

### LINKED ISSUE #948: Cannot build Chainer with numpy 1.11b3
I cannot install chainer with numpy 1.11b3. It is because `numpy.core` doesn't exist in this version.
We need to restrict version of numpy.

### PR DESCRIPTION
**Pull request by okuta**
Fix #948

### CODE REVIEW

**Comment by unnonouno** [comment]
`reload(numpy)` is reuiqred.
See http://www.programcreek.com/python/example/67000/builtins.__NUMPY_SETUP__

**Comment by okuta** [comment]
Thank you for your information.
I fixed.

**Comment by unnonouno** [comment]
I couldn't run this code on python 3.4. Please check it.

**Comment by unnonouno** [comment]
This patch works correctly. My old environment was broken. LGTM

**Pull request merged**
