### PR TITLE
Add consistency check of backward propagation between 2D and ND pooling functions

### LINKED ISSUE #2109: Add consistency check of backward propagation between 2D and ND pooling function
We have unittests that checks consistency of forward methods of 2D and ND pooling. But not for backward methods. Although the combination of forward consistency check and ordinal unittests for  backward propagation implicitly check the consistency, such unittests would strengthen the code.

### PR DESCRIPTION
**Pull request by takagi**
Fix #2109.

This PR adds a test to check consistency of backward methods of 2D and ND pooling layers:
- max pooling layer
- average pooling layer

### CODE REVIEW

**Comment by takagi** [comment]
Pooling|CPU/cuDNN/CuPy|forward/backward|Status
-|-|-|-
Max pooling|CPU|forward|Doing
Max pooling|CPU|backward|Doing
Max pooling|cuDNN|forward|Doing
Max pooling|cuDNN|backward|Doing
Max pooling|CuPy|forward|Doing
Max pooling|CuPy|backward|Doing
Average pooling|CPU|forward|Doing
Average pooling|CPU|backward|Doing
Average pooling|cuDNN|forward|Doing
Average pooling|cuDNN|backward|Doing
Average pooling|CuPy|forward|Doing
Average pooling|CuPy|backward|Doing

**Comment by takagi** [comment]
I have finished to implement the test for consistency check between 2D and ND pooling layers. This PR eventually covers the tests for the following conditions extending the original issue #2109:

- Max pooling layer / Average pooling layer
- CPU / cuDNN / CuPy implementations
- forward / backward computation

**Comment by delta2323** [comment]
LGTM, I am running Jenkins to see if all GPU will pass successfully.

**Comment by delta2323** [comment]
LGTM

**Pull request merged**
