### PR TITLE
Merge v1.24 to v2

### PR DESCRIPTION
**Pull request by unnonouno**
I merged v1.24.0 fixes to v2.

### CODE REVIEW

**Comment by niboshi** [comment]
Can you fix test errors?

**Comment by ronekko** [comment]
Hi, I wrote some necessary modifications from current master to v2 for GoogLeNet.
https://github.com/pfnet/chainer/compare/master...ronekko:googlenet-for-v2

**Comment by okuta** [comment]
I got error in `/tests/chainer_tests/links_tests/model_tests/test_vision.py`.
Cloud you check it?

**Comment by niboshi** [comment]
I merged @ronekko's modification and made some fixes.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
