### PR TITLE
Add functions.absolute

### LINKED ISSUE #1575: Add chainer.functions.abs
Current `Variable` requires `chainer.functions.sum` for the sum function but builtin `abs` for the absolute function. Builtin `sum` should not be used for a `Variable` and there is no `abs` in `chainer.functions`.

### PR DESCRIPTION
**Pull request by unnonouno**
fix #1575

### CODE REVIEW

**Comment by gwtnb** [comment]
LGTM

**Comment by gwtnb** [comment]
I think a user expect `abs` because the corresponding builtin function's name is `abs`.

**Comment by unnonouno** [comment]
NumPy has `numpy.absolute`.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
