### PR TITLE
Implement chainer.testing.product and , cupy.testing.product

### PR DESCRIPTION
**Pull request by delta2323**
This PR implements `chainer.testing.product` and `cupy.testing.product`. Basic usage (and implementation itself) is same as that of `maflib.util.product` ([Link](https://pfi.github.io/maf/maflib.html#maflib.util.product)).

### CODE REVIEW

**Comment by unnonouno** [comment]
Do we need to write test code for this method?

**Comment by delta2323** [comment]
Actually, yes. I will write it.

**Comment by delta2323** [comment]
I added unit tests.

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
