### PR TITLE
Remove requirement that inputs of VAE functions being Variable

### PR DESCRIPTION
**Pull request by delta2323**
Currently, inputs of VAE functions (`gaussian_kl_divergence`, `bernoulli_nll`, and `gaussian_nll`) must be `Variable`. But as Chainer function accepts `xp.ndarray` as well as `Variable` (see #1221). This requirement is too restrictive. This PR loosen the type condition of their inputs.

### CODE REVIEW

**Comment by unnonouno** [comment]
Can you check mixed situation?

**Comment by delta2323** [comment]
I added test cases.

**Comment by unnonouno** [comment]
Check travis.

**Comment by unnonouno** [comment]
Rebase the master

**Comment by unnonouno** [comment]
check test result

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
