### PR TITLE
Rename unary_math_function_test

### LINKED ISSUE #1740: Rename unary_math_function_test.py
`nose` searches test files using [a regex](http://nose.readthedocs.io/en/latest/usage.html#extended-usage). It matches to `unary_math_function_test.py`, so we have to rename before releasing 1.17.0.

### PR DESCRIPTION
**Pull request by delta2323**
Fix #1740. Related #1534.

### CODE REVIEW

**Comment by gwtnb** [comment]
It seems better to add `_` prefix (e.g. `_unary_math_function_unittest`, `_unary_math_function_test.py` for a while to rename the entities in future.

**Comment by gwtnb** [comment]
Documents should be fixed. https://github.com/pfnet/chainer/pull/1534/files#diff-6e9377c0cf634ee425fa26edc48c3e6a

**Comment by delta2323** [comment]
> It seems better to add _ prefix (e.g. _unary_math_function_unittest, _unary_math_function_test.py for a while to rename the entities in future.

You mean we should change the names temporally? If so, I am afraid I am not sure why we should do so.

**Comment by gwtnb** [comment]
> You mean we should change the names temporally?

Yes.

If an entity will be renamed, users should not use it. Adding `_` prefix is an easy way to express that the entity is private. Ref: https://github.com/pfnet/chainer/issues/1716

**Comment by delta2323** [comment]
What I am not sure is that why should it be temporal? Do you think we should remove the prefix `_` again? 

The developers of Chainer functions can use this decorator to test them. So another question is that users in this context is those who do not create official Chainer functions, isn't it?

**Comment by gwtnb** [comment]
> What I am not sure is that why should it be temporal?

If the name is good to use for long time, we do not have to add `_`. I will merge this to

**Pull request merged**
