### PR TITLE
Improve docs of dstack

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
This is PR for improving docs of functions/links. Related issue: #2182

Modified functions/links:
 - functions/array/dstack

### CODE REVIEW

**Comment by delta2323** [comment]
LGTM

**Comment by soramichi** [comment]
Why is the newline in between `>>> x1 = np.arrange(0, 6).reshape(3, 2)` and `>>> x1.shape` missing in the screen shot?

**Comment by keisuke-umezawa** [comment]
@soramichi 
The screen shot is the first commit version. Sorry not to replace the images.

**Comment by soramichi** [comment]
Oops, sorry, I should have checked each commit carefully.

**Pull request merged**
