### PR TITLE
Add AlexNet to Imagenet example

### PR DESCRIPTION
**Pull request by delta2323**
AlexNet used in `imagenet` example is different from original one in that Local Response Normalization(LRN) layers are replaced with Batch Normalizations(BN) (so, the architecture name is `alexbn` rather than `alex`). The reason for this change is that LRN was not implemented at the time the example is made. This PR implements original AlexNet and adds it to `imagenet` example.

### CODE REVIEW

**Comment by okuta** [comment]
The original AlexNet has layers which are divided into two at channel axis.
Its structure has been reproduced in caffe.
What do you think is good for us.

**Comment by delta2323** [comment]
Ah, sorry. I missed the structure. I think we can defer the implementation of the feature until we need to reproduce the result exactly. In that case, we should add comment the difference of my implementation and original one.

**Comment by okuta** [comment]
OK. Please add comment.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
