### PR TITLE
Remove Parameter link

### LINKED ISSUE #2177: Remove Parameter link
`chainer.links.Parameter` link is deprecated and should be dropped in v2.

### PR DESCRIPTION
**Pull request by delta2323**
Fix #2177

### CODE REVIEW

**Comment by unnonouno** [comment]
Please rebase the master for jenkins.

**Comment by delta2323** [comment]
As this is a PR for the base branch, I thought the base branch would be `_v2` and integration of  changes that have applied to the master branch will be done to this branch through `_v2` branch. Do I misunderstand something?

**Comment by unnonouno** [comment]
Sorry. Merge _v2.

**Comment by delta2323** [comment]
Sorry, I could not understand what you wanted to do. The goal of this PR is to be merged to `_v2`. So, it is strange that I (the author of this PR) merge this PR by myself.

**Comment by beam2d** [comment]
I guess Unno-san is talking about rebasing this branch on top of the current _v2 so that Jenkins can run the tests for this branch.

**Comment by delta2323** [comment]
Ah, I see. Sorry for my mistake. I seems to have been a little tired...

**Comment by unnonouno** [comment]
not _v1 but _v2

**Comment by delta2323** [comment]
Sorry, I should have explained it. I could have merged _v2 branch correctly as you can see from the network. It seems I wrongly rewrite the commit message when I merge the branch.



But as travis is failing, I will fix the code later.

**Comment by delta2323** [comment]
This PR is built on top of #2367. So, please merge #2367 first.

**Comment by unnonouno** [comment]
Check jenkins and remove test_parameter.py

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
