### PR TITLE
Make a global variable that enables type check

### LINKED ISSUE #371: Make a method to disable type check
Type checking is large overhead. We need to make a method to disable it.
related to #333

### PR DESCRIPTION
**Pull request by unnonouno**
fix #371

### CODE REVIEW

**Comment by beam2d** [comment]
How about making it a class attribute of Function class? I also want an environment variable to configure this flag.

**Comment by unnonouno** [comment]
I'll make a global variable `function.default_type_check_enable` and a local variable `type_check_enable` to `Function`.

**Comment by unnonouno** [comment]
OK, i made a class variable `type_check_enable`. A user can also set this variable of each function.

**Comment by beam2d** [comment]
[LGTM](http://lgtm.in/i/2loA5WA1q)

**Comment by beam2d** [comment]
Thanks!

**Pull request merged**
