### PR TITLE
Change default behavior of accept_error

### LINKED ISSUE #1419: Errors in numpy-cupy comparison tests are ignored if accept_error=True by default
`cupy.testing` has decorators for comparing results from numpy and cupy functions such as `numpy_cupy_array_equal`. In these decorators, `accept_error=True` by default, so even if test code has typo or access to undefined names, they would pass. Such decorators are used everywhere without specifying `accept_error=False`: https://github.com/pfnet/chainer/search?utf8=%E2%9C%93&q=numpy_cupy_array_equal&type=Code 

For example, https://github.com/pfnet/chainer/pull/1404 has typo in test code, calling `xp.fill_diag` instead of `xp.fill_diagonal`, but the tests pass. I suppose errors should not be ignored by default. It would be better to have users to specify which type of errors should be accepted.

### PR DESCRIPTION
**Pull request by unnonouno**
I fixed default argument of numpy-cupy comparison. And, I set `accept_error=True` for only tests which raises errors.
fix #1419

### CODE REVIEW

**Comment by gwtnb** [comment]
Some tests failed: 
```
FAIL: test_argmax_nan (test_search.TestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 364, in test_func
    impl(self, *args, **kw)
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 88, in test_func
    accept_error=accept_error)
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 57, in _check_cupy_numpy_error
    self.fail(msg)
AssertionError: Both cupy and numpy raise exceptions

cupy
Traceback (most recent call last):
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 20, in _call_func
    result = impl(self, *args, **kw)
  File "/home/foo/chainer/chainer/tests/cupy_tests/sorting_tests/test_search.py", line 28, in test_argmax_nan
    a = xp.array([float('nan'), -1, 1], dtype)
  File "/home/foo/chainer/chainer/cupy/creation/from_data.py", line 27, in array
    return core.array(obj, dtype, copy, ndmin)
  File "cupy/core/core.pyx", line 1478, in cupy.core.core.array (cupy/core/core.cpp:49630)
    cpdef ndarray array(obj, dtype=None, bint copy=True, Py_ssize_t ndmin=0):
  File "cupy/core/core.pyx", line 1492, in cupy.core.core.array (cupy/core/core.cpp:49246)
    a_cpu = numpy.array(obj, dtype=dtype, copy=False, ndmin=ndmin)
ValueError: cannot convert float NaN to integer

numpy
Traceback (most recent call last):
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 20, in _call_func
    result = impl(self, *args, **kw)
  File "/home/foo/chainer/chainer/tests/cupy_tests/sorting_tests/test_search.py", line 28, in test_argmax_nan
    a = xp.array([float('nan'), -1, 1], dtype)
ValueError: cannot convert float NaN to integer


-------------------- >> begin captured stdout << ---------------------
dtype is <class 'numpy.int8'>

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_argmin_nan (test_search.TestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 364, in test_func
    impl(self, *args, **kw)
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 88, in test_func
    accept_error=accept_error)
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 57, in _check_cupy_numpy_error
    self.fail(msg)
AssertionError: Both cupy and numpy raise exceptions

cupy
Traceback (most recent call last):
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 20, in _call_func
    result = impl(self, *args, **kw)
  File "/home/foo/chainer/chainer/tests/cupy_tests/sorting_tests/test_search.py", line 70, in test_argmin_nan
    a = xp.array([float('nan'), -1, 1], dtype)
  File "/home/foo/chainer/chainer/cupy/creation/from_data.py", line 27, in array
    return core.array(obj, dtype, copy, ndmin)
  File "cupy/core/core.pyx", line 1478, in cupy.core.core.array (cupy/core/core.cpp:49630)
    cpdef ndarray array(obj, dtype=None, bint copy=True, Py_ssize_t ndmin=0):
  File "cupy/core/core.pyx", line 1492, in cupy.core.core.array (cupy/core/core.cpp:49246)
    a_cpu = numpy.array(obj, dtype=dtype, copy=False, ndmin=ndmin)
ValueError: cannot convert float NaN to integer

numpy
Traceback (most recent call last):
  File "/home/foo/chainer/chainer/cupy/testing/helper.py", line 20, in _call_func
    result = impl(self, *args, **kw)
  File "/home/foo/chainer/chainer/tests/cupy_tests/sorting_tests/test_search.py", line 70, in test_argmin_nan
    a = xp.array([float('nan'), -1, 1], dtype)
ValueError: cannot convert float NaN to integer


-------------------- >> begin captured stdout << ---------------------
dtype is <class 'numpy.int8'>

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 10748 tests in 275.356s

FAILED (SKIP=1, failures=2)
```

**Comment by boeddeker** [comment]
Maybe there should be an further option "exception_class" like in numpy.testing.assert_raises to specify the type of the exception.

An example starting point:
https://github.com/fgnt/chainer/commit/116ca8e9331c4069e3234859417d990601d947af

**Comment by unnonouno** [comment]
@boeddeker Thank you a good suggestion! `accept_exception_class` is enough, because when a user want to accept any types of exception, he just need to add `accept_exception_class=Exception`. It has the same meaning as `accept_error=True`.

**Comment by unnonouno** [comment]
I updated the implementation to accept both `bool` and `type`.

**Comment by gwtnb** [comment]
LGTM

**Pull request merged**
