### PR TITLE
Fix document of chainer.util.experimental

### PR DESCRIPTION
**Pull request by delta2323**
I used direct import of modules as `from chainer.utils import experimental` in the document of `chainer.util.experimental` for simplicity. But I come to think it is not appropriate as we use this function when we develop Chainer itself, which forbits direct import of modules by pep8. So I have fixed to obey pep8.

I have also fixed small document typo.

### CODE REVIEW

**Comment by unnonouno** [comment]
Why did the original code pass the test?

**Comment by delta2323** [comment]
Are you thinking of the change from `chainer.experimental.f` to `chainer.foo.bar.f` ? That is where I  was wondering, too. I will investigate it.

**Comment by unnonouno** [comment]
If the document test did not find a problem of your old document, that means the test does not work. You need to fix the test first.

**Comment by delta2323** [comment]
I agree.

**Comment by delta2323** [comment]
I submitted the PR that fixes the doctest as #1972 . Please merge the PR before this.

**Comment by unnonouno** [comment]
I merged #1972. Please merge/rebase it.

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
