### PR TITLE
[WIP] Implement unpooling.

### PR DESCRIPTION
**Pull request by nushio3**
This patch adds `unpooling_2d` function as used e.g. in http://arxiv.org/abs/1411.5928 .
Implements #172 .
However, I believe that the unpooing function preferably should  be implemented based on `Function` class, rather than as a composite function.

I appreciate advice on how to implement an instance of Function class...
Also I'd like to ask what kind of test we'd like to have.

### CODE REVIEW

**Comment by nushio3** [comment]
Oops, this PR does not even builds ... I need first study how to build the package properly.

**Comment by delta2323** [comment]
Unpooling2D is implemented and under review in #599. We will close this PR after #599 is merged.

**Comment by nushio3** [comment]
Good to hear that! In fact, I have been stumbled at the point of setting up the python library development environment (I've never done this before and am clueless,) and there was little hope that I can make progress in near future. So I'm glad that this function is covered by Chainer developers.

**Comment by delta2323** [comment]
@nushio3  We merged Unpooling2D as PR #599. Please give it a try.

**Comment by nushio3** [comment]
:+1:

**Pull request closed without merging**
