### PR TITLE
Fix 0-size malloc

### PR DESCRIPTION
**Pull request by okuta**
This PR fix error at the time of gpu memory release.

### CODE REVIEW

**Comment by unnonouno** [comment]
Can you write a test for this patch?

**Comment by delta2323** [comment]
I run the test code you added without applying this PR and found that it does not fail. So I am afraid the test code cannot check it does solve the error.

**Comment by unnonouno** [comment]
OK, please add `assertNotIsInstance(mem, PooledMemory)`.

**Comment by okuta** [comment]
Thank you for the information.
I fixed the test case.

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
