### PR TITLE
Use nogil statements to enable cupy to use async callback

### PR DESCRIPTION
**Pull request by okuta**
This PR fixes dead locking.

### CODE REVIEW

**Comment by gwtnb** [comment]
Could you describe how a deadlock occurs?

**Comment by okuta** [comment]
This PR is needed by #1707, because it uses async callback.

**Comment by rezoo** [comment]
I briefly read this PR, and it seems good.

**Comment by rezoo** [comment]
Are there any reasons why ``setStream`` and ``getStream`` do not use ``with noggin:`` statement?

**Comment by rezoo** [comment]
I also think that this PR involves ``enhancement`` or ``feature`` label rather than ``bug``.

**Comment by okuta** [comment]
> Are there any reasons why getStream and setStream do not use with nogil: statement?
I don't know about need or not need nogil statement in this case.

> It seems that this PR involves enhancement or feature label rather than bug.
OK, Please change it.

**Comment by rezoo** [comment]
Thanks. I would like to merge this one.

**Pull request merged**
