### PR TITLE
Add contribution guidelines under .github

### PR DESCRIPTION
**Pull request by niboshi**
This PR is for #2750.

* [CONTRIBUTING.md](https://github.com/pfnet/chainer/blob/dot-github/.github/CONTRIBUTING.md)
* [ISSUE_TEMPLATE.md](https://github.com/pfnet/chainer/blob/dot-github/.github/ISSUE_TEMPLATE.md)
* [PULL_REQUEST_TEMPLATE.md](https://github.com/pfnet/chainer/blob/dot-github/.github/PULL_REQUEST_TEMPLATE.md)

`CONTRIBUTING.md` is simply copied from `docs/source/contribution.rst` and markups has been fixed for markdown.

See also: https://github.com/blog/1184-contributing-guidelines

Also added `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md`.

### CODE REVIEW

**Comment by delta2323** [comment]
Although this PR is valid for v1, should we retarget this PR to v2?

**Comment by delta2323** [comment]
Can you change the source branch with the one prefixed with `_v2`?

**Comment by niboshi** [comment]
OK. I'll recreate another PR.

**Comment by niboshi** [comment]
Reposted here: #2774

**Pull request closed without merging**
