### PR TITLE
[WIP] Fix imagenet for windows to use if __name__ == "__main__" idiom

### PR DESCRIPTION
**Pull request by delta2323**
According to Sikon-san's report on Google Group, imagenet example does not run properly on Windows environment. If the main scripts uses multiprocessing module, we need to disable side effects in main scripts by using `__name__ == "__main__"` idiom.
See [the official document](https://docs.python.org/2/library/multiprocessing.html?highlight=multiprocessing#windows) for details.

### CODE REVIEW

**Comment by unnonouno** [comment]
Do anyone have Windows environment to test this PR?

**Comment by okuta** [comment]
The following error occurred on Windows.
```
Z:\env\chainer2\chainer\examples\imagenet>python train_imagenet.py --gpu 0 f:\ILSVRC\val.txt f:\ILSVRC\val.txt --mean mean.npy
epoch 1
learning rate 0.01

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train_imagenet.py", line 305, in <lambda>
    feeder = threading.Thread(target=lambda: feed_data(model.insize))
  File "train_imagenet.py", line 135, in feed_data
    x_batch[j] = x.get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
NameError: global name 'mean_image' is not defined
```

**Comment by delta2323** [comment]
Oh, sorry. It seems so a stupid error.

**Comment by okuta** [comment]
```Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train_imagenet.py", line 305, in <lambda>
    feeder = threading.Thread(target=lambda: feed_data(model.insize, train_list, val_list, mean_image))
  File "train_imagenet.py", line 135, in feed_data
    x_batch[j] = x.get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
TypeError: read_image() takes at most 4 arguments (5 given)```

**Comment by delta2323** [comment]
As implementation is halfway and obsolete, we close this PR and reopen as an issue.

**Pull request closed without merging**
