### PR TITLE
Insert function label in initializer of InvalidType exception for readable stack-trace

### LINKED ISSUE #2081: Readable stack trace in type-check
In Function._check_data_type_forward, it re-raises a new exception object for a detailed error message. Instead it hides the original stack-trace. It is useless for users to know details of type error.

### PR DESCRIPTION
**Pull request by unnonouno**
I used thread-local variable to check a label of a current function.
fix #2081

### CODE REVIEW

**Comment by okuta** [comment]
LGTM!

I think this PR is enhancement. Therefore I will merge it.
Do you agree @unnonouno?

**Comment by unnonouno** [comment]
Yes, I think so. BTW, do you think the name of this method adequate?

**Comment by okuta** [comment]
How about `get_function_check_context`?

**Comment by unnonouno** [comment]
Sounds good!

**Comment by gwtnb** [comment]
It seems that raising an exception with another exception's stack trace by using `six.reraise`. Is it infeasible to use `six.reraise`?

**Comment by okuta** [comment]
The stack track form `six.reraise` is difficult that output two exception information.
Therefore, this PR is useful. What do you think about this?

**Comment by okuta** [comment]
I understood `raise_from` and `reraise`.
`raise_from` do not work on Python2,
https://github.com/benjaminp/six/blob/master/six.py#L732

`six.reraise` is good for this problem.

**Comment by unnonouno** [comment]
Python3 uses raise_from for `six.reraise` and it shows two stacktrace:
```
% cat reraise.py
import six
import sys

try:
    raise Exception('a')
except Exception as e:
    six.reraise(ValueError, ValueError('b'), sys.exc_info()[2])
```
```
% python reraise.py
Traceback (most recent call last):
  File "reraise.py", line 5, in <module>
    raise Exception('a')
Exception: a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reraise.py", line 7, in <module>
    six.reraise(ValueError, ValueError('b'), sys.exc_info()[2])
  File "/home/unno/.pyenv/versions/3.5.1/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "reraise.py", line 5, in <module>
    raise Exception('a')
ValueError: b
```
This error message is confusing for me.

**Comment by unnonouno** [comment]
And `raise_from`:
```
% python reraise.py
Traceback (most recent call last):
  File "reraise.py", line 5, in <module>
    raise Exception('a')
Exception: a

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "reraise.py", line 7, in <module>
    six.raise_from(ValueError('b'), e)
  File "<string>", line 2, in raise_from
ValueError: b```

**Comment by unnonouno** [comment]
In this case, `raise_from` is better than `reraise`. But I like simpler one.

**Comment by okuta** [comment]
OK, I understood. 
This PR provides readable stack-trace.

LGTM!

**Pull request merged**
