### PR TITLE
add axis option and apply cupy for functions.Sum

### PR DESCRIPTION
**Pull request by kikusu**
Add axis option like numpy.sum for functions.Sum

```
s = list(x[0].shape)
s[self.axis] = 1
gy = gy[0].reshape(s)
```
If `cupy.expand_dims` is implemented, this cord is replaced with `gy = xp.expand_dims(gy[0], axis=self.axis)`

### CODE REVIEW

**Comment by okuta** [comment]
Thank you for your PR.
I implemented expand_dims #343.
I propose the code below.

```python
gx = xp.empty_like(x[0])
gx[:] = xp.expand_dims(gy[0], axis=self.axis)
```

**Comment by kikusu** [comment]
Thank you for code review.
I revised PR in a suggested code using expand_dims.

**Comment by okuta** [comment]
Great!

Please write document about axis.

https://github.com/pfnet/chainer/blob/v1.2.0/chainer/functions/concat.py#L90
Please use it as a reference.

**Comment by kikusu** [comment]
I added document.
Is it acceptable for you?

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
Thank you.

**Pull request merged**
