### PR TITLE
Fix array

### LINKED ISSUE #639: cupy.array cause segmentation fault
Hi, I have been playing with cupy today and find a bug.

The following code result in `Segmentation fault (core dumped)`

```pyton
import cupy
x = cupy.random.rand(100, 10)
cupy.array([x[0], x[1]])
```

thanks.

### PR DESCRIPTION
**Pull request by okuta**
fix #639

### CODE REVIEW

**Comment by unnonouno** [comment]
LGTM!

**Comment by bupt-renpei** [comment]
Sorry for bothering. I'm using the chainer v1.24.0, and when i test the example (python chainer-1.24.0/examples/cifar/train_cifar.py), i still encounter the problem "Segmentation fault (core dumped)", but it's ok for mnist example (python chainer-1.24.0/examples/mnist/train_mnist.py) on both CPU and GPU. Looking forward to your reply!

**Comment by okuta** [comment]
Hmm, It is strange. Currently, Chainer only uses pure Python. I do not know why cause segmentation fault.
Cloud you send core dump or stacktrace by GDB?

https://www.akadia.com/services/ora_enable_core.html

**Comment by bupt-renpei** [comment]
Hi, thank you for your reply! Here is the report.

root@cheng-PowerEdge-T630:/home/cheng/rp/chainer/chainer-1.24.0/examples/cifar# python train_cifar.py 
Segmentation fault (core dumped)

root@cheng-PowerEdge-T630:/home/cheng/rp/chainer/chainer-1.24.0/examples/cifar# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515101
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 515101
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

root@cheng-PowerEdge-T630:/home/cheng/rp/chainer/chainer-1.24.0/examples/cifar# exit

cheng@cheng-PowerEdge-T630:~$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515101
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 515101
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

cheng@cheng-PowerEdge-T630:~$ sudo su
[sudo] password for cheng: 

root@cheng-PowerEdge-T630:/home/cheng# python rp/chainer/chainer-1.24.0/examples/cifar/train_cifar.py 
Segmentation fault (core dumped)
root@cheng-PowerEdge-T630:/home/cheng#

**Comment by okuta** [comment]
You can see ` core.PID` file cloud you share that file?

**Pull request merged**
