### PR TITLE
fix to_gpu() of Convolution2D

### PR DESCRIPTION
**Pull request by xternalz**
When the 'Convolution2D' function is migrated to GPU, it doesn't create the variable 'max_workspace_size' for the operation in cuDNN mode.

### CODE REVIEW

**Comment by unnonouno** [comment]
Than you for your patch.
Please write details of your situation. Do you have a minimum code to check this bug?

**Comment by xternalz** [comment]
It happens when you pickle a model through a non-GPU machine, and then you load the pickled model to a GPU machine. In the non-GPU situation, `cuda.cudnn_enabled` is  `False` and hence `max_workspace_size` is not created:

```
# from convolution_2d.py
if cuda.cudnn_enabled and use_cudnn:
            # chance to choose implicit-precomp-gemm algorithm
            self.max_workspace_size = in_channels * self.kh * self.kw * 4
```

**Comment by unnonouno** [comment]
OK, you are right. I think calculation of `max_wordspace_size` is very light. So, it is enough to remove the condition `if cuda.cudnn_enabled and use_cudnn:` in `__init__` method, isn't it?

**Comment by xternalz** [comment]
I think so. I have made the changes according to what you suggested. Please check it again.

**Comment by unnonouno** [comment]
Thank you! Great work!

**Pull request merged**
