### PR TITLE
Use skcuda module

### LINKED ISSUE #198: Use `skcuda` module instead of `scikits.cuda`
`scikits.cuda` module is deprecated. Replace it with `skcuda`.

### PR DESCRIPTION
**Pull request by unnonouno**
fix #198

### CODE REVIEW

**Comment by unnonouno** [comment]
Note that this patch destroy the compatibility. Users who installed `scikits.cuda` by hands need to install new `scikit-cuda`.

**Comment by beam2d** [comment]
It seems the old scikits.cuda also exposes the `skcuda` package that points to the same objects hierarchy as that of `scikits.cuda`, so this PR may keep the compatibility, though I cannot try it since I do not have an environment with scikits.cuda any more :(
https://github.com/lebedov/scikit-cuda/tree/0.5.0b2/skcuda

**Comment by unnonouno** [comment]
I'll try it

**Comment by unnonouno** [comment]
Oh, we already checks if `scikit-cuda` exists. `scikits.cuda` already doesn't work...

**Comment by beam2d** [comment]
You are right, so we need not concern about scikits.cuda any more!!

**Comment by beam2d** [comment]
[LGTM](http://lgtm.in/i/CbqeKakFn)

**Comment by beam2d** [comment]
Thank you!

**Pull request merged**
