### PR TITLE
Write test for int operators of ndarray

### LINKED ISSUE #444: Test binary operators for int
There are no test for int operators, such as `__and__`.

### PR DESCRIPTION
**Pull request by unnonouno**
I wrote a test for int operators (and, or, xor, {l,r}shift) for `ndarray`.
fix #444

### CODE REVIEW

**Comment by okuta** [comment]
Why don’t you add test for `__invert__`?

**Comment by unnonouno** [comment]
This test only includes binary operators.  I'll write a test for `__invert__` and other unary operators in another PR.

**Comment by delta2323** [comment]
@unnonouno  Could you submit the issue beforehand?

**Comment by unnonouno** [comment]
I made an issue #444

**Comment by okuta** [comment]
LGTM!

**Comment by delta2323** [comment]
@unnonouno Thanks!

**Pull request merged**
