### PR TITLE
Remove links alias under chainer.functions

### LINKED ISSUE #2321: Remove alias of links under chainer.functions namespace
We left these alias only for backward compatibility.

### PR DESCRIPTION
**Pull request by delta2323**
Fix #2321

### CODE REVIEW

**Comment by unnonouno** [comment]
Please rebase master

**Comment by delta2323** [comment]
As this is a PR for _v2, I thought the base branch would be _v2 and integration of changes that have applied to the master branch will be done to this branch through _v2 branch. Do I misunderstand something?

**Comment by unnonouno** [comment]
Ah, sorry merge _v2.

**Comment by unnonouno** [comment]
Fix the document and the examples which uses these links.

**Comment by delta2323** [comment]
I believe these links, which located under `chainer.functions` namespace are deprecated and not used in document nor examples. But I will check if they remain.

**Comment by unnonouno** [comment]
check jenkins

**Comment by delta2323** [comment]
@unnonouno Thank you for pointing out the problem. I will take over this PR to you when I confirm that the tests in Jenkins pass.

**Comment by delta2323** [comment]
I think I fixed the problem.

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
