### PR TITLE
Negative sampling ignore

### PR DESCRIPTION
**Pull request by unnonouno**
This PR fix negative sampling function to support ignore label. The original PR is #1045. Thank you @cemoody !

### CODE REVIEW

**Comment by okuta** [comment]
Please add `test_ignore_forward_cpu` and `test_ignore_backward_cpu`.

**Comment by okuta** [comment]
LGTM except comment.

**Comment by okuta** [comment]
OK!

**Comment by cemoody** [comment]
Thanks for looking this over! Sorry I missed the original comments!

**Comment by unnonouno** [comment]
No problem! And, thank you for your contribution and sorry for the slow review.

**Pull request merged**
